-- Budget Tree — AI reflections
--
-- Stores the periodic AI "reflection" summaries (weekly / monthly) generated by
-- the ai-coach edge function so they persist across devices. One row per user
-- per period instance, keyed by (user_id, period, period_start) so a given week
-- or month is only ever generated once. Per-user RLS: you can read and write
-- only your own reflections.

create table if not exists public.ai_reflections (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references auth.users on delete cascade,
  period       text not null,            -- weekly | monthly
  period_start date not null,            -- first day of the week/month it covers
  text         text not null,
  created_at   timestamptz not null default now(),
  unique (user_id, period, period_start)
);

create index if not exists ai_reflections_user_created_idx
  on public.ai_reflections (user_id, created_at desc);

alter table public.ai_reflections enable row level security;

drop policy if exists "read own reflections" on public.ai_reflections;
create policy "read own reflections" on public.ai_reflections
  for select
  using (auth.uid() = user_id);

drop policy if exists "insert own reflections" on public.ai_reflections;
create policy "insert own reflections" on public.ai_reflections
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "delete own reflections" on public.ai_reflections;
create policy "delete own reflections" on public.ai_reflections
  for delete
  using (auth.uid() = user_id);
